// ============================================================
// WasteWise — Recommendations Page (Connected to REST API & Engine)
// ============================================================
import { useState } from 'react';
import {
  AlertTriangle, TrendingDown, CheckCircle2, DollarSign,
  Lightbulb, ChevronRight, Check, X, BarChart2, Info
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import type { Recommendation, RecommendationPriority } from '../types';
import { recommendationService } from '../services/recommendationService';
import { showToast } from '../components/ui/Toast';

const priorityConfig = {
  High: { icon: <AlertTriangle size={20} />, color: 'high', badge: 'danger', label: 'High Priority' },
  Medium: { icon: <TrendingDown size={20} />, color: 'medium', badge: 'orange', label: 'Medium Priority' },
  Low: { icon: <Info size={20} />, color: 'low', badge: 'info', label: 'Low Priority' },
  Positive: { icon: <CheckCircle2 size={20} />, color: 'positive', badge: 'success', label: 'Positive Insight' },
};

export default function Recommendations() {
  const { state, dispatch } = useApp();
  const [filter, setFilter] = useState<RecommendationPriority | 'All'>('All');
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const recommendations = state.recommendations.filter(r => {
    if (filter !== 'All' && r.priority !== filter) return false;
    return true;
  });

  const active = recommendations.filter(r => r.status === 'Active');
  const applied = recommendations.filter(r => r.status === 'Applied');
  const dismissed = recommendations.filter(r => r.status === 'Dismissed');

  const handleApply = async (id: string) => {
    try {
      await recommendationService.updateStatus(id, 'Applied');
      dispatch({ type: 'UPDATE_RECOMMENDATION_STATUS_LOCAL', payload: { id, status: 'Applied' } });
      showToast({ type: 'success', title: 'Recommendation applied!', message: 'Status updated in database.' });
    } catch (err: any) {
      showToast({ type: 'error', title: 'Failed to update', message: err.message });
    }
  };

  const handleDismiss = async (id: string) => {
    try {
      await recommendationService.updateStatus(id, 'Dismissed');
      dispatch({ type: 'UPDATE_RECOMMENDATION_STATUS_LOCAL', payload: { id, status: 'Dismissed' } });
      showToast({ type: 'info', title: 'Recommendation dismissed', message: 'You can reactivate it anytime.' });
    } catch (err: any) {
      showToast({ type: 'error', title: 'Failed to update', message: err.message });
    }
  };

  const handleReactivate = async (id: string) => {
    try {
      await recommendationService.updateStatus(id, 'Active');
      dispatch({ type: 'UPDATE_RECOMMENDATION_STATUS_LOCAL', payload: { id, status: 'Active' } });
      showToast({ type: 'success', title: 'Recommendation reactivated' });
    } catch (err: any) {
      showToast({ type: 'error', title: 'Failed to update', message: err.message });
    }
  };

  const handleViewAnalysis = () => {
    dispatch({ type: 'SET_PAGE', payload: 'analytics' });
  };

  return (
    <div>
      {/* Header Stats */}
      <div className="kpi-grid" style={{ marginBottom: 24 }}>
        {[
          { label: 'Active', count: state.recommendations.filter(r => r.status === 'Active').length, color: 'var(--color-primary)' },
          { label: 'Applied', count: state.recommendations.filter(r => r.status === 'Applied').length, color: 'var(--color-info)' },
          { label: 'Dismissed', count: state.recommendations.filter(r => r.status === 'Dismissed').length, color: 'var(--text-tertiary)' },
          { label: 'High Priority', count: state.recommendations.filter(r => r.priority === 'High' && r.status === 'Active').length, color: 'var(--color-danger)' },
        ].map((s, i) => (
          <div key={i} className="card animate-in" style={{ animationDelay: `${i * 0.05}s` }}>
            <div style={{ fontSize: 30, fontWeight: 800, color: s.color }}>{s.count}</div>
            <div style={{ fontSize: 13, color: 'var(--text-secondary)', marginTop: 4 }}>{s.label} Recommendations</div>
          </div>
        ))}
      </div>

      {/* Note */}
      <div style={{
        background: 'var(--badge-info-bg)', border: '1px solid #bae6fd',
        borderRadius: 10, padding: '12px 16px', marginBottom: 20,
        display: 'flex', gap: 10, alignItems: 'flex-start', fontSize: 13
      }}>
        <Lightbulb size={16} color="var(--color-info)" style={{ flexShrink: 0, marginTop: 1 }} />
        <span style={{ color: 'var(--text-secondary)' }}>
          <strong style={{ color: 'var(--text-primary)' }}>Rule-Based Recommendation Engine</strong> — 
          These recommendations are dynamically generated by analyzing your SQLite waste database.
        </span>
      </div>

      {/* Filters */}
      <div className="filters-bar" style={{ marginBottom: 20 }}>
        {(['All', 'High', 'Medium', 'Low', 'Positive'] as const).map(f => (
          <button
            key={f}
            className={`btn btn-sm ${filter === f ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => setFilter(f)}
          >
            {f === 'All' ? 'All' : priorityConfig[f as RecommendationPriority]?.label || f}
          </button>
        ))}
      </div>

      {/* Active Recommendations */}
      {active.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 12, color: 'var(--text-primary)' }}>
            Active Recommendations ({active.length})
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {active.map((rec, i) => (
              <RecCard
                key={rec.id}
                rec={rec}
                expanded={expandedId === rec.id}
                onToggle={() => setExpandedId(expandedId === rec.id ? null : rec.id)}
                onApply={() => handleApply(rec.id)}
                onDismiss={() => handleDismiss(rec.id)}
                onViewAnalysis={handleViewAnalysis}
                delay={i * 0.05}
              />
            ))}
          </div>
        </div>
      )}

      {/* Applied */}
      {applied.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 12, color: 'var(--text-primary)' }}>
            Applied ({applied.length})
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {applied.map(rec => (
              <div key={rec.id} className="card" style={{ opacity: 0.75 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <div style={{ width: 36, height: 36, borderRadius: 10, background: 'var(--badge-success-bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                    <Check size={18} color="var(--color-success)" />
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontWeight: 600, fontSize: 14 }}>{rec.title}</div>
                    <div style={{ fontSize: 12, color: 'var(--color-success)', marginTop: 2 }}>✓ Applied</div>
                  </div>
                  <button
                    className="btn btn-secondary btn-sm"
                    onClick={() => handleReactivate(rec.id)}
                  >
                    Reactivate
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Dismissed */}
      {dismissed.length > 0 && (
        <div>
          <h3 style={{ fontSize: 15, fontWeight: 600, marginBottom: 12, color: 'var(--text-tertiary)' }}>
            Dismissed ({dismissed.length})
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {dismissed.map(rec => (
              <div key={rec.id} className="card" style={{ opacity: 0.5 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                  <div style={{ flex: 1, fontSize: 14, fontWeight: 500 }}>{rec.title}</div>
                  <button
                    className="btn btn-secondary btn-sm"
                    onClick={() => handleReactivate(rec.id)}
                  >
                    Restore
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {recommendations.length === 0 && (
        <div className="empty-state">
          <div className="empty-state-icon"><Lightbulb size={24} /></div>
          <h3>No recommendations for this filter</h3>
          <p>Try selecting a different priority filter.</p>
        </div>
      )}
    </div>
  );
}

// ─── Recommendation Card ──────────────────────────────────
function RecCard({ rec, expanded, onToggle, onApply, onDismiss, onViewAnalysis, delay }: {
  rec: Recommendation;
  expanded: boolean;
  onToggle: () => void;
  onApply: () => void;
  onDismiss: () => void;
  onViewAnalysis: () => void;
  delay: number;
}) {
  const cfg = priorityConfig[rec.priority] || priorityConfig.Medium;
  return (
    <div className={`rec-card animate-in`} style={{ animationDelay: `${delay}s`, flexDirection: 'column' }}>
      <div style={{ display: 'flex', gap: 16 }}>
        <div className={`rec-icon ${cfg.color}`}>{cfg.icon}</div>
        <div style={{ flex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10, marginBottom: 6 }}>
            <div style={{ flex: 1 }}>
              <span className={`badge badge-${cfg.badge}`} style={{ marginBottom: 6, display: 'inline-block' }}>{cfg.label}</span>
              <h4 style={{ fontSize: 15, fontWeight: 700, color: 'var(--text-primary)' }}>{rec.title}</h4>
            </div>
            <button className="btn btn-ghost btn-icon" onClick={onToggle} style={{ flexShrink: 0 }}>
              <ChevronRight size={16} style={{ transform: expanded ? 'rotate(90deg)' : 'none', transition: 'transform 0.2s' }} />
            </button>
          </div>
          <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{rec.description}</p>
        </div>
      </div>

      {expanded && (
        <div style={{ marginTop: 16, paddingTop: 16, borderTop: '1px solid var(--border-color)' }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(200px,1fr))', gap: 16, marginBottom: 16 }}>
            <div>
              <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginBottom: 4 }}>Suggested Action</div>
              <div style={{ fontSize: 13, color: 'var(--text-primary)', lineHeight: 1.5 }}>{rec.suggestedAction}</div>
            </div>
            <div>
              <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginBottom: 4 }}>Expected Impact</div>
              <div style={{ fontSize: 13, color: 'var(--text-primary)', lineHeight: 1.5 }}>{rec.impact}</div>
            </div>
            <div>
              <div style={{ fontSize: 11, color: 'var(--text-tertiary)', marginBottom: 4 }}>Estimated Savings</div>
              <div style={{ fontSize: 15, fontWeight: 700, color: 'var(--color-success)' }}>
                <DollarSign size={13} style={{ display: 'inline' }} />{rec.estimatedSavings}
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            <button className="btn btn-primary btn-sm" onClick={onApply}>
              <Check size={14} /> Apply Recommendation
            </button>
            <button className="btn btn-secondary btn-sm" onClick={onViewAnalysis}>
              <BarChart2 size={14} /> View Analysis
            </button>
            <button className="btn btn-ghost btn-sm" style={{ color: 'var(--text-tertiary)' }} onClick={onDismiss}>
              <X size={14} /> Dismiss
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
